pluginManagement {
	repositories {
		mavenLocal()
		mavenCentral()
		gradlePluginPortal()
		maven { url = 'https://maven.fabricmc.net/' }
		maven {
			name = 'KikuGie Releases'
			url = 'https://maven.kikugie.dev/releases'
		}
		maven {
			name = 'KikuGie Snapshots'
			url = 'https://maven.kikugie.dev/snapshots'
		}
	}
}

plugins {
	id 'dev.kikugie.stonecutter' version '0.9.7'
	id 'dev.kikugie.loom-back-compat' version '0.4'
}

stonecutter {
	create(rootProject) {
		versions '1.21.4', '1.21.11', '26.2', '26.3'
		vcsVersion = '26.3'
	}
}

rootProject.name = 'EvMod'