name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**' # Trigger only if files inside the website/ folder change
  pull_request:
    branches:
      - main
    paths:
      - 'website/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: EvModder/PNG-to-NBT
          path: png-to-nbt
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: website/.bun-version
      - run: bun ci
      - run: bun run sync:map-colors -- ../png-to-nbt/website/src/data/mapColors.ts
      - run: bun run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: website/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
